---
version: 2
updates:

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 100
    ignore:
      - dependency-name: "*"
        update-types: [ "version-update:semver-patch" ]